### ISSUE TITLE
DotNet proxy times out after some time in ArcGIS 10.3

### ISSUE THREAD

**Issue by laythg** [Esri/resource-proxy#185]
The proxy works ok after issue #177 was resolved.  However, after an hour or so calls to the proxy return a error 498, invalid token.  Restarting IIS or recycling the Worker assigned to the Proxy web app makes it start working again for another hour.

Possibly a short-lived token not being renewed or something?

**Comment by esoekianto** [comment]
@laythg I remember we had similar issue before, can you check if you have this line in the proxy.ashx? https://github.com/Esri/resource-proxy/blob/master/DotNet/proxy.ashx#L375

**Comment by laythg** [comment]
Yes Irwin, I have that line in the version I'm using.  I am running the version of the proxy I got directly from you.

**Comment by MikeTschudi** [comment]
Found two cases where proxy stopped working after a block of time:
1. Geoenrichment service returns formatted invalid token error code, which includes spaces that aren't recognized when proxy.ashx tries to catch this case, so token doesn't get reauthorized.
2. The cast ```ConcurrentDictionary<string, RateMeter> ratemap = (ConcurrentDictionary<string, RateMeter>)context.Application["rateMap"];``` is occasionally throwing an exception; see http://stackoverflow.com/questions/6370252/random-invalidcastexception for a discussion.

Clone branch https://github.com/MikeTschudi/resource-proxy/tree/normalize_error_code addresses the first case by removing spaces and newlines before checking for ```"{\"error\":{"```, ```"\"code\":498"```, and ```"\"code\":499"```.

Clone branch {https://github.com/MikeTschudi/resource-proxy/tree/wrap_cast addresses the second case by wrapping the ConcurrentDictionary cast in a try-catch block and resetting the ratemap if the exception is thrown.

We're testing these now and will propose them as pull requests if testing continues to go well.
@lindsayking @bsvensson

**Comment by laythg** [comment]
Actually I was able to fix the issue (I think).  Haven't seen it for a while.  The issue is that (in my install anyway) when the token times out in ArcGIS 10.3 is is returning the ArcGIS REST API Login page.  So I modified the code in fetchAndPassBackToClient() to look like this:

                        if (
                            !ignoreAuthenticationErrors
                            && strResponse.IndexOf("{\"error\":{") > -1
                            && (strResponse.IndexOf("\"code\":498") > -1 || strResponse.IndexOf("\"code\":499") > -1)
                            || strResponse.IndexOf("REST API Login") > -1  // Added by Layth Grangaard.  This is what ArcGIS SErver 10.3 seems to return.
                        )
                            return true;

Let me know if this doesn't look right.  But as I said, the proxy has been working OK for me since I made this change.

**Comment by laythg** [comment]
An update.  When using this proxy against a 10.3 Server, the first request for a token works.  However, once that token expires and it tries to renew, Server is returning an error message.  Here is the log results for the renewal exchange:

w3wp.exe Information: 0 : 2015-01-21 01:18:58 Sending request!
w3wp.exe Information: 0 : 2015-01-21 01:19:04 https://www.irmdgisdev.org/arcgis/rest/
w3wp.exe Information: 0 : 2015-01-21 01:19:04 Sending request!
w3wp.exe Information: 0 : 2015-01-21 01:19:04 Renewing token and trying again.
w3wp.exe Information: 0 : 2015-01-21 01:19:04 Matching credentials found in configuration file. OAuth 2.0 mode: False
w3wp.exe Information: 0 : 2015-01-21 01:19:04  Querying security endpoint...
w3wp.exe Information: 0 : 2015-01-21 01:19:04 Sending request!
w3wp.exe Information: 0 : 2015-01-21 01:19:05  Service is secured by https://www.irmdgisdev.org/arcgis/tokens/: getting new token...
w3wp.exe Information: 0 : 2015-01-21 01:19:05  URI for token will be: https://www.irmdgisdev.org/arcgis/tokens?request=gettoken?f=json&expiration=60&referer=http://localhost:49279/MapViewer?Length=0&ParcID=48049000046&expiration=10&username=THEUSER&password=THEPASSWD
w3wp.exe Information: 0 : 2015-01-21 01:19:05 Sending request!
w3wp.exe Information: 0 : 2015-01-21 01:19:05  Token obtained: Invalid request <br>Usage: https://www.irmdgisdev.org/arcgis/tokens?request=gettoken&username=username&password=password&<br>Usage: https://www.irmdgisdev.org/arcgis/tokens/generateToken?username=username&password=password&<br>Usage: https://www.irmdgisdev.org/arcgis/tokens/gettoken.html<br>
w3wp.exe Information: 0 : 2015-01-21 01:19:05 Sending request!

I verified the user and password are correct in the renewal call.  But Server is returning the error message instead of the token.  I have sanitized the log output to remove the username and password obviously.

**Comment by esoekianto** [comment]
@laythg I can reproduce the same issue using Java proxy accessing 10.3. We will investigate this further.

**Comment by laythg** [comment]
Irwin,

It was related to having a query string as part of the URL when the the
token is renewed.  I can send you the modifications I made to fix my issue.

Layth

°o°

**Comment by esoekianto** [comment]
@laythg oh please send it to us or make pull request

**Comment by masbis** [comment]
Hello @laythg, I also have the same problem. My installation is with ArcGIS Portal Server 10.3.1. Could you give me directions on the solution? Many thanks

**Comment by bsvensson** [comment]
The original issue here about renewing tokens has been fixed in #254 (DotNet), and also for JSP in #245 and for PHP in #272.

**Comment by upcamogie** [comment]
I still have this type of issue and am using the latest dotnet proxy. i am running server 10.2.1 at the moment. has this issue really been resolved fully? i have been dealing with inconsistency for weeks

**Comment by sebaspelletier** [comment]
I still have this type of issue and am using the latest dotnet proxy. I use ClientId and ClientSecret on ArcGIS Online. When the proxy make  "renewing token" the result is always "Invalid Token". At the next proxy call the respond il always OK.

**Comment by kkerbel** [comment]
Like sebaspelletier, I too am still having this issue with the newest version of the proxy. Should we use a different version or something?  Thanks! Kit

**Comment by sebaspelletier** [comment]
Check my new post : https://github.com/Esri/resource-proxy/issues/338
